# Shell variables
# Generated by 'wal'
wallpaper='/home/karster/Pictures/Screenshots/Screenshot from 2022-10-13 03-18-05.png'

# Special
background='#16141c'
foreground='#e9dde9'
cursor='#e9dde9'

# Colors
color0='#16141c'
color1='#C9A3BC'
color2='#A59FD0'
color3='#B1A8D3'
color4='#D2B0D0'
color5='#E6B7D4'
color6='#DDBBE6'
color7='#e9dde9'
color8='#a39aa3'
color9='#C9A3BC'
color10='#A59FD0'
color11='#B1A8D3'
color12='#D2B0D0'
color13='#E6B7D4'
color14='#DDBBE6'
color15='#e9dde9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
