--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/karster/Pictures/Screenshots/Screenshot from 2022-10-13 03-18-05.png"

-- Special
background="#16141c"
foreground="#e9dde9"
cursor="#e9dde9"

-- Colors
color0="#16141c"
color1="#C9A3BC"
color2="#A59FD0"
color3="#B1A8D3"
color4="#D2B0D0"
color5="#E6B7D4"
color6="#DDBBE6"
color7="#e9dde9"
color8="#a39aa3"
color9="#C9A3BC"
color10="#A59FD0"
color11="#B1A8D3"
color12="#D2B0D0"
color13="#E6B7D4"
color14="#DDBBE6"
color15="#e9dde9"
