#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom -f &
polybar &
./.fehbg &
wal -Rqn &

bspc monitor -d I II III IV V VI

bspc config border_width            1
bspc config window_gap              3
bspc config pointer_follows_focus   true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
